/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20260210T133239"   // DateTime using ISO-8601 format
        " "                 // alignment
        "6e247b5c"          // STLIB commit
        "--------"          // ADJ commit
        "4ca846f9"          // Board commit
        // the '=' is used for unparsing
        ;
}