/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20260123T214025"   // DateTime using ISO-8601 format
        " "                 // alignment
        "e2a56178"          // STLIB commit
        "--------"          // ADJ commit
        "1b75e823"          // Board commit
        // the '=' is used for unparsing
        ;
}